### ISSUE TITLE
Unit test feedback

### ISSUE THREAD

**Issue by Anisha7** [MakeMeSenpai/spaceman#1]
You run the tests you implemented! They are only defined. Run these functions! When you do, you'll see that there are quite a few errors with your tests. You are trying to use undefined variables inside your test functions. Come to office hours to better understand how tests are written and how they function! The following steps would help you organize your code better so its easier to understand:
- Its good practice to separate your test code into a different file! Try doing this. Import your spaceman.py into a test file and move your tests in there. 
- Wrap any functions running globally in `if __name__ == '__main__':`. Doing so will only run game program functions when `python3 spaceman.py` is run in the terminal.

**Comment by The1stAnthony** [comment]
- got rid of broken tests
- added `if __name__ == '__main__'` before function run
